# Generated by Django 4.2.1 on 2023-06-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_date_time_order_has_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent',
            new_name='stripe_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='has_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('AWAITING', 'AWAITING'), ('SUCCESSFUL', 'SUCCESSFUL')], default='PENDING', max_length=10),
        ),
    ]
